# Generated by Django 5.1.6 on 2025-04-17 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_plantsale_date_listed_alter_plantsale_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsale',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
